apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: operational
resources:
  - ../../../kustomize
components:
  - ../../../kustomize/components/network-policies
patches:
  - path: loadgenerator-init-resources.yaml
