apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: oracle
resources:
  - ../../../kustomize
components:
  - ../../../kustomize/components/network-policies
  - ../../../kustomize/components/non-public-frontend
  - ../../../kustomize/components/without-loadgenerator
